name: Deploy

on:
  push:
    branches:
      - main
jobs:
  database-migrations:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm i
      - name: Run prisma migrations
        run: npx prisma migrate deploy
      - name: Seed database
        run: npm run seed

  deploy-to-vercel:
    needs: database-migrations
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Create env variables
        run: |
          echo "${{ secrets.DATABASE_URL }}" >> .env
          vercel env add DATABASE_URL production --sensitive --token=${{ secrets.VERCEL_TOKEN }} < .env
          rm .env
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
